language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g yarn
- cp ./src/example.config.js ./src/config.js
install:
- yarn
script:
- if [ "TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/decrypt.sh; fi
- yarn build
- yarn lint
- yarn test
before_install:
- openssl aes-256-cbc -K $encrypted_eeb74e8d35d1_key -iv $encrypted_eeb74e8d35d1_iv
  -in .env.enc -out .env -d
